dateModified: 1737941535
email:
  fromEmail: test@example.com
  fromName: 'Simple Craft'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      addSubfolderToRootUrl: false
      autoFocalPoint: false
      bucket: $CRAFT_S3_BUCKET
      bucketSelectionMode: manual
      cfDistributionId: $CRAFT_CLOUDFRONT_ID
      cfPrefix: ''
      expires: ''
      keyId: ''
      makeUploadsPublic: false
      region: $CRAFT_S3_REGION
      secret: ''
      storageClass: ''
      subfolder: ''
    type: craft\awss3\Fs
    url: $CRAFT_ASSET_BASE_URL
meta:
  __names__:
    09da7654-c0fb-4278-8e4b-8ffc523e7795: 'Simple Craft' # Simple Craft
    761cc5b5-d64d-43ae-96ce-6338303579c3: 'Simple Craft' # Simple Craft
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
system:
  edition: solo
  live: true
  name: 'Simple Craft'
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
