---
- name: "EC2 Bastion Setup"
  become: true
  hosts: default

  pre_tasks:
    - name: "Update apt cache"
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: "../roles/ec2-base"
