---
php_version: 8.2
extra_php_extensions: []

php_memory_limit: 256M
php_max_execution_time: 120
php_opcache_enabled: 1
php_max_filesize: 64M
php_post_max_size: 64M
php_max_input_vars: 2000

php_cli_memory_limit: 256M
php_cli_max_execution_time: 120
php_cli_max_filesize: 64M
php_cli_post_max_size: 64M
