---
- name: add utilities for apt repository management
  apt:
    name:
      - python3-apt
      - python3-pycurl
    state: present

- name: add ondrej nginx repository
  apt_repository:
    repo: ppa:ondrej/nginx
    state: present

- name: install nginx
  apt:
    name:
    - nginx
    - brotli
    - libnginx-mod-http-brotli
    state: present
