name: Build Artifact and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - sample-application/**/*
permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: ./sample-application
env:
  AWS_EXECUTION_ROLE: ${{secrets.AWS_EXECUTION_ROLE}}
jobs:
  BuildArtifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.AWS_EXECUTION_ROLE}}
          aws-region: us-east-1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Build Composer Deps
        run: composer install
      - name: Build NPM Deps
        run: npm ci
#       For simplicity the sample application has no css/js to be built
#      - name: Build assets
#        run: npm run prod
      - name: Package application
        run: tar --exclude='.env' --exclude -czf example-application-${{github.sha}} .
      - name: Copy package to S3
        run: aws s3 copy example-application-${{github.sha}} s3://fly-ue1-dev-example-application-artifact-786781442308818825
