name: Build Artifact and Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
  push:
    branches:
      - dev
    paths:
      - sample-application/**/*
permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: ./sample-application
jobs:
  BuildArtifact:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-22.04
    env:
      AWS_EXECUTION_ROLE_ARN: ${{secrets.AWS_EXECUTION_ROLE_ARN}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.AWS_EXECUTION_ROLE_ARN}}
          aws-region: us-east-1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Build Composer Deps
        run: composer install
      - name: Build NPM Deps
        run: npm ci
#       For simplicity the sample application has no css/js to be built
#      - name: Build assets
#        run: npm run prod
      - name: Package application
        run: tar --exclude='.env' --exclude -czf example-application-${{github.sha}} .
      - name: Copy package to S3
        run: aws s3 copy example-application-${{github.sha}} ${{vars.ARTIFACT_S3_BUCKET}}
