name: 🚀 DEV - Build Artifact and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - example-application/**/*
permissions:
  id-token: write
  contents: read
jobs:
  DevBuildArtifact:
    name: Dev Build Artifact
    secrets: inherit
    uses: ./.github/workflows/reusable-build.yaml
    with:
      ENVIRONMENT: dev
  DevDeploy:
    name: Dev Deploy
    needs: DevBuildArtifact
    secrets: inherit
    uses: ./.github/workflows/reusable-instance-refresh.yaml
    with:
      ENVIRONMENT: dev
