name: 🚀 PROD - Build Artifact and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - prod
permissions:
  id-token: write
  contents: read
jobs:
  BuildArtifact:
    name: Build Artifact
    secrets: inherit
    uses: ./.github/workflows/reusable-build.yaml
    with:
      ENVIRONMENT: prod
  Deploy:
    name: Deploy
    needs: BuildArtifact
    secrets: inherit
    uses: ./.github/workflows/reusable-instance-refresh.yaml
    with:
      ENVIRONMENT: prod
